# this docker file starts and runs MacOS
# for instructions, see here: https://github.com/dockur/macos

# start the container with: docker compose up
# stop the container with: docker stop macos

services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "14"
      CPU_CORES: "4"
      RAM_SIZE: "16G"
      DISK_SIZE: "128G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - /home/bob/vm/dockur/macos/storage:/storage
      - /home/bob/vm/dockur/macos/share:/shared
#    restart: unless-stopped
    stop_grace_period: 2m